version: '2'
services:
    leaderboard-server:
        platform: linux/arm64
        container_name: leaderboard
        build:
            dockerfile: Dockerfile
        image: leaderboard:latest
        ports:
            - 8080:8080
        networks:
            - spring-cloud-network
networks:
    spring-cloud-network:
        driver: bridge