version: '2'
services:
  leaderboard-server:
    build:
      dockerfile: Dockerfile
    image: leaderboard:latest
    ports:
      - 8080
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge